<?php

/**
 * @file
 * Alternative Pager ( Example ).
 *
 * Example work module.
 */

/**
 * Implements hook_menu().
 */
function altpager_example_menu() {
  $items['altpager_example'] = array(
    'title' => 'Alternative Pager',
    'page callback' => 'altpager_example_page',
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Example page.
 */
function altpager_example_page() {
  altpager_items_elements(array(
    1 => 1,
    2 => 2,
    5 => 5,
  ));

  $query = db_select('node', 'n')->extend('AltPager');
  $nids = $query
    ->fields('n', array('nid'))
    ->orderBy('created', 'DESC')
    ->execute()
    ->fetchAll();

  $pager = theme('altpager');

  $result = $pager;

  foreach ($nids as $row) {
    $node = node_load($row->nid);
    $result .= render(node_view($node));
  }

  $result .= theme('altpager');

  return $result;
}
